# Generated by Django 5.2.8 on 2025-12-03 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sentmail_sender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='group',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='core.organisation'),
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('organisation', 'name')},
        ),
        migrations.RemoveField(
            model_name='group',
            name='user',
        ),
    ]
